322 write unit tests for form controller components
justifi-tech/web-component-library pull request #452
Opened 2024-04-17 14:29 UTC by TiagoFuelber

This adds unit tests for form-controller components

Links
-----
#322 

Developer considerations
--------------

- On any task
  - [ ] Previous unit and e2e tests are passing
  - [ ] Perform dev QA

Developer QA steps
--------------------

2024-04-17 16:38 UTC, jakemer requested changes

2024-04-17 17:15 UTC, TiagoFuelber commented on packages/webcomponents/src/components/form/form-control-select.tsx
> +          {this.options?.length && this.options.map(option => (
Good deal! This was breaking some tests, but I simple optional chaining here is a way better fix.

2024-04-17 18:28 UTC, jakemer approved these changes

2024-04-18 16:02 UTC, colganmeanor commented
Approved Dev QA

🪇

2024-04-18 18:20 UTC, colganmeanor approved these changes

2024-04-18 18:22 UTC, merged